### ISSUE TITLE
How should I redevelop the project?

### ISSUE THREAD

**Issue by AGDholo** [ttskch/vuepress-theme-blog-vuetify#13]
Hello,
I really like this project, but the layout is different from what I want, how should I start debugging locally? I don't see any instructions that can be used.
Thanks.

**Comment by ttskch** [comment]
@AGDholo

Sorry for my late response. Maybe you can redevelop this project by following steps.

1. `git clone` this repo
2. `cd example`
3. edit package.json
```diff
- "vuepress-theme-blog-vuetify": "^1"
+ "vuepress-theme-blog-vuetify": ".."
```
4. `npm install`
5. `npm run dev`
6. you can see the site at http://localhost:8080
7. after you modified some theme files, you have to stop dev-server and run `npm install` each time

Thanks.
